baseurl = "http://www.diversal.se/"
languageCode = "en-us"
title = "Diversal Consulting"
theme = "hugo-creative-theme"

[params]
	name = "Diversal"
	description = "devops, continuous delivery, deploy, jenkins, kubernetes, docker, drone"
	favicon = "favicon.ico" 	# The path must be relative to the static folder


	# Navigation
	[params.navigation]
		brand = "Diversal"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


		# Hero section
		[params.hero]
			# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
			slogan     = "<img src='img/diversallogo_white.png' width='90%'>"
			subtitle   = "Devops, CD"


		#	About section
		[params.about]
			#	headline    = "559069-7602"
			#	description = "Org. Nr: 559069-7602"#
			#	buttonText  = "Get started!"


	  # Portfolio modals
		[params.portfolio.modal]
	    client = "Client"
	    date = "Date"
	    category = "Category"
	    buttonText = "Close"

		# Contact section
		[params.contact]
			headline = ""
			description = " "
			phone = "+46709450857"
			email = "info@diversal.se"
			org = "ORG:559069-7602"
			vat = "VAT:SE559069760201"
			linkedin = "http://linkedin.com/in/jgunnarsson"
			linkedinshort = "jgunnarsson"
